### ISSUE TITLE
Markdown Import pod does not update links referencing assets

### ISSUE THREAD

**Issue by Harshita-mindfire** [dendronhq/dendron#1237]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The assets are imported in assets folder, but the links referencing assets remains the same after importing
with markdown pod. 

## To Reproduce

assets folder structure of source to import 

    |--images
          |---2021-07-25-12-25-06.png

md file referencing asset has the following link
```
![](/images/2021-07-25-12-25-06.png)
```

assets Folder structure of vault after running markdown import

 ```
assets
     |---2021-07-25-12-25-06-wV4ld9vIX4pL.png
```
md file referencing it remains
```
![](/images/2021-07-25-12-25-06.png)
```
## Expected behavior

md file referencing it should update the link as
```
![](/assets/2021-07-25-12-25-06-wV4ld9vIX4pL.png)
```
## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by hikchoi** [comment]
Thanks for the report @Harshita-mindfire :) Are you going to be taking this item yourself?

**Comment by Harshita-mindfire** [comment]
Sure @hikchoi, assigning to self.

**Comment by Harshita-mindfire** [comment]
This should be fixed in v0.59 of Dendron. Please post here if not, otherwise this issue will auto close in 4 days

**Comment by sotn3m** [comment]
There is one additional scenario that does not work. Two examples:
``` 
folder
    |--- media
    |     |--- image.png
    |     |--- same_level.md
    |--- something.md
```
The contents of `same_level.md`: 
```markdown
![](image.jpg)
![](./image.jpg)
```
The contents of `something.md`:
```markdown
![](media/image.jpg)
![](./media/image.jpg)
```
None of the 4 links are updated.

In essence, relative links are not updated at the moment.

**Comment by tgrosinger** [comment]
I'm still experiencing issues with this. I am importing a markdown Vault from Obsidian. I have a structure like this:

```
folder
  |---assets
  |------|---image.JPEG
  |---something.md
```
The contents of `something.md` before import were:

```
![[image.JPEG]]
```

After the import, `something.md` became:

```
![[image.JPEG|image.jpeg]]
```

And the file became `folder/assets/image-UQPiIa1nvvBq.JPEG`. Dendron is not able to find the image from the note anymore.

This is definitely a show stopper for me being able to use Dendron.

**Comment by sotn3m** [comment]
It is also failing when folder is in capital letters. Please see Folder2 under [markdown import](https://github.com/sotn3m/markdown-import).

**Comment by Harshita-mindfire** [comment]
Hello @sotn3m, you are right there is an issue with importing assets when the folder is in caps. Will be adding a quick fix for this.

**Comment by Harshita-mindfire** [comment]
Hi @sotn3m, this has been fixed with Dendron v0.82. Please let us know if it continues to happen, otherwise, this issue will close in a few days.
