### ISSUE TITLE
Cannot build site due to dependency error (11ty) 

### ISSUE THREAD

**Issue by parthmshah1302** [dendronhq/dendron#1324]
- [X] Publish. Sharing your repo with the world
## Describe the bug

Dependency error of 11ty on siteBuild.

## To Reproduce

1. Dendron: Site Build

## Expected behavior

Site is built at x location. 

## Screenshots

![image](https://user-images.githubusercontent.com/59203561/132959869-799ea99d-7b4c-4739-907a-cda49405a5e7.png)

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: Chrome

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/7148421/dendron.log)

**Comment by kevinslin** [comment]
thanks for the report. this should now be fixed with 0.58.3

**Comment by parthmshah1302** [comment]
Hey Kevin!
I am still facing the issue 
```
error running command: Command failed with exit code 4294963248: npm install --save @dendronhq/dendron-11ty@1.58.4
npm ERR! code EPERM
npm ERR! syscall rmdir
npm ERR! path c:\Users\parth\Desktop\Code\Notes\node_modules\.staging\get-stream-90b62ddd
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rmdir 'c:\Users\parth\Desktop\Code\Notes\node_modules\.staging\get-stream-90b62ddd'
npm ERR!  [Error: EPERM: operation not permitted, rmdir 'c:\Users\parth\Desktop\Code\Notes\node_modules\.staging\get-stream-90b62ddd'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: 'c:\\Users\\parth\\Desktop\\Code\\Notes\\node_modules\\.staging\\get-stream-90b62ddd'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

```

I am pretty sure this is not a permissions issue. 
The log file can be found [here](https://gist.github.com/parthmshah1302/61ce4791d1bfc321f75d524a1df630e0)

[2021-09-13T16_17_16_020Z-debug.log](https://github.com/dendronhq/dendron/files/7155874/2021-09-13T16_17_16_020Z-debug.log)

**Comment by kevinslin** [comment]
We had a regression with the last 11ty publishing. Can you update to the latest version of the CLI and 11ty by following the setup instructions [here](https://wiki.dendron.so/notes/1399b5d2-28fb-4077-aa5f-c8edbe52bc5d.html#setup)?
