### ISSUE TITLE
Cmd + Enter doesn't navigate to links from editor on macOS?

### ISSUE THREAD

**Issue by d1rewolf** [dendronhq/dendron#1750]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Describe the bug

I'm walking through the tutorial, and it states:

*To navigate to the note in the link, you can just click on the link in the preview pane. In the editor pane, you can move the cursor into the link and hit `Cmd+Enter`.*

However, on my system (macOS Monterey), if I do this in the editor, it simply moves the cursor to the next line.

## To Reproduce

1. Disable all extensions to ensure none are interfering.
2. Go to 'tutorial.3-linking-your-notes.md'
3. Place cursor in 'Example: [[tutorial]]' on line 15. Make sure to place within the [[ ]].
4. Press Cmd + Enter
5. Witness cursor simply move to next line.

## Expected behavior

Per the tutorial, it should navigate to link just like Cmd + click does.

## Desktop (please complete the following information)

- OS: macOS Monterey

## Additional context
VSCode version info:
Version: 1.62.0 (Universal)
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:24:41.297Z (2 wks ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
[dendron.log](https://github.com/dendronhq/dendron/files/7572272/dendron.log)

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by d1rewolf** [comment]
Update: after some discussion on Discord, it seems ctrl+enter works, while cmd+enter doesn't. Either the tutorial is wrong, or the plugin is.

**Comment by hikchoi** [comment]
Thanks for letting us know. This is definitely an inconsistency between the plugin and the tutorial.

the current keybinding for `Go to Note` is indeed `ctrl+enter`.

defined here: 

```json
...
{
        "command": "dendron.gotoNote",
        "key": "ctrl+enter",
        "when": "editorFocus"
},
...
```

Pinging @jonathanyeung for tutorial related issue. Did we intend to have a mac specific keybinding here or have it be `ctrl` for mac as well? In any case, I think we should keep it as-is at this point since changing it would affect all existing mac users.

**Comment by kevinslin** [comment]
this should be fixed in v70 of Dendron. please post here if not, otherwise this issue will auto close in 4 days

**Comment by rubinj30** [comment]
I just downloaded this extension and am going through the tutorial and noticed that the CMD + ENTER (on MacOS) still does not do anything, as tutorial says it should.
