### ISSUE TITLE
Error t.assertUnreachable when trying Export Pod V2 on a new vault on Windows

### ISSUE THREAD

**Issue by blu3r4y** [dendronhq/dendron#1838]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [X] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When I try to use the "Export Pod V2" functionality, after finishing the initial configuration, I will receive the following error.
The other "Export Pod" function does work as expected - the error happens only with V2.

```
DendronError: This error should never occur! Please report a bug if you have encountered this.
    at t.assertUnreachable (c:\\Users\\mario\\.vscode\\extensions\\dendron.dendron-0.71.0\\dist\\extension.js:2:103643)
    at Wn.enrichInputs (c:\\Users\\mario\\.vscode\\extensions\\dendron.dendron-0.71.0\\dist\\extension.js:8:3297044)
    at Wn.run (c:\\Users\\mario\\.vscode\\extensions\\dendron.dendron-0.71.0\\dist\\extension.js:8:3066460)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## To Reproduce

1. Initialize a new native workspace with the default preset
2. Run Export Pod V2 and finish the initial configuration (use `MarkdownExportV2` for the entire vault, save to local filesystem)
3. You will see the error

## Expected behavior

That my vault is exported to Markdown.

## Desktop

- OS: Windows 11, Version 21H2
- VS Code: 1.62.3 (Chrome 91.0.4472.164)
- Version: v0.71.0

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/7653759/dendron.log)

**Comment by kevinslin** [comment]
Thanks for the issue. This should be fixed in today's release of Dendron

**Comment by blu3r4y** [comment]
@jonathanyeung Could you reopen this please? The bug is still there, but the error message changed slightly. Even tried it on a different computer this time.

```
DendronError: This error should never occur! Please report a bug if you have encountered this.
    at t.assertUnreachable (c:\\Users\\Mario\\.vscode\\extensions\\dendron.dendron-0.72.0\\dist\\extension.js:2:103950)
    at An.enrichInputs (c:\\Users\\Mario\\.vscode\\extensions\\dendron.dendron-0.72.0\\dist\\extension.js:8:3157513)
    at An.run (c:\\Users\\Mario\\.vscode\\extensions\\dendron.dendron-0.72.0\\dist\\extension.js:8:3223611)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Desktop

- OS: Windows 10, Version 21H1
- VS Code: 1.63.0 (Chromium: 91.0.4472.164)
- Version: v0.72.0

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/7697349/dendron.log)

**Comment by kevinslin** [comment]
@blu3r4y we made some fixes to this, can you confirm if you still see this issue after the 0.73 release tomorrow?

**Comment by blu3r4y** [comment]
Tried it with Dendron v0.73.0 and the error still exists 😄 
Is this something I can help debugging locally? 🤔 

```
DendronError: This error should never occur! Please report a bug if you have encountered this.
    at t.assertUnreachable (c:\\Users\\mario\\.vscode\\extensions\\dendron.dendron-0.73.0\\dist\\extension.js:2:106166)
    at Rr.enrichInputs (c:\\Users\\mario\\.vscode\\extensions\\dendron.dendron-0.73.0\\dist\\extension.js:8:3198360)
    at Rr.run (c:\\Users\\mario\\.vscode\\extensions\\dendron.dendron-0.73.0\\dist\\extension.js:8:3051274)
    at processTicksAndRejections (internal/process/task_queues.js:93:5
```

```json
{
   "level":50,
   "time":1639548768212,
   "pid":19464,
   "hostname":"MARIO-NCASE",
   "name":"dendron",
   "ctx":"dendron.markdownexportv2:run",
   "error":{
      "stack":"DendronError: This error should never occur! Please report a bug if you have encountered this.\n    at t.assertUnreachable (c:\\Users\\mario\\.vscode\\extensions\\dendron.dendron-0.73.0\\dist\\extension.js:2:106166)\n    at Rr.enrichInputs (c:\\Users\\mario\\.vscode\\extensions\\dendron.dendron-0.73.0\\dist\\extension.js:8:3198360)\n    at Rr.run (c:\\Users\\mario\\.vscode\\extensions\\dendron.dendron-0.73.0\\dist\\extension.js:8:3051274)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
      "message":"This error should never occur! Please report a bug if you have encountered this.",
      "name":"DendronError",
      "status":"unknown",
      "payload":"{}"
   }
}
```

**Comment by kevinslin** [comment]
hmm, does this still repro on 0.74? can you walk me through how you are running the pod (with the yml configuration)?

**Comment by aleksey-rowan** [comment]
It does fail in 0.74 as well. 

I'm using the following config:

```yml
podId: ec-bs-2
exportScope: Vault
podType: MarkdownExportV2
wikiLinkToURL: false
destination: c:\Users\AR\Desktop\blah
```

Running `Dendron: Export Pod V2` gives the "This error should never occur!" error.

**Comment by Harshita-mindfire** [comment]
Hey @blu3r4y @aleksey-rowan, This should be fixed in the latest releases of Dendron(v0.105). Feel free to ping here if it still throw an error.

**Comment by blu3r4y** [comment]
The export is working now, thanks @Harshita-mindfire 🥳
