### ISSUE TITLE
Improve accessibility in Preview Pane

### ISSUE THREAD

**Issue by jquesada2016** [dendronhq/dendron#2012]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features
- [ x ] Accessibility

## Describe the bug

I am a user who is legally blind and rely on accessibility tools that read what's on the screen. I can see somewhat, so don't therefore need a full blown screen reader, as VS Code covers this. However, I do rely on a tool which reads content from the clipboard. This is a problem because `Dendtron's Preview Pane` does not support copying selected text, and thus cannot get the tool I use to read aloud the contents.

## To Reproduce

1. Open anything in Dendron such that you get a `Preview Pane`.
2. Select text from the `Preview Pane`.
3. Try pasting the copied content.
4. Observe that nothing is pasted.

## Expected behavior

I expect selecting and copying text from the `Preview Pane` to actually copy the selected content.

## Desktop (please complete the following information)

- OS: Windows 11
- Browser: N/A
- Version: N/A

## Additional context

The content that is actually copied to the clipboard is a `null` value. This is actually what my clipboard reader says aloud.

**Comment by jquesada2016** [comment]
Hopefully this issue isn't the end of the world! ;) #2012

**Comment by dokmanc** [comment]
Not having the ability to copy from the Preview Pane might not be the end of the world but for me, it's the end of considering Dendron. I'm surprised that  you would not realize that this could be a deal breaker.

**Comment by Harshita-mindfire** [comment]
Hello @jquesada2016, Thanks for reporting the issue. I can repro this one and will be fixing this in the upcoming releases. This is a recently introduced bug that works fine till the dendron release v0.73.

**Comment by kevinslin** [comment]
this issue should be fixed with the latest release! (0.78)

**Comment by tommcc** [comment]
Thanks, team! It works! 🎉

**Comment by dokmanc** [comment]
Copying the HTML from the Preview pane still doesn't work for me.

I see two related buttons on the document tab:

  1. Dendron: Show Preview
  2. Markdown Preview Enhanced: Open Preview to the Side (Ctrl+ K V)

When I use the first, a pane opens to the right and I see a preview of the current markdown. when I select all of the text in the preview pane and I right mouse click and select the "Copy" context menu and paste into Notepad, I see that only the last word is copied.

When I click the second preview button, nothing happens. I add in _Dendron Markdown Preview preview Enhanced_ is installed and enabled. Disabling it doesn't improve the functionality of the original button (1).
