### ISSUE TITLE
Inconsistent layout of mobile view of published pages

### ISSUE THREAD

**Issue by andrey-jef** [dendronhq/dendron#2175]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When reading some specific pages in Dendron wiki with images, i have to manually zoom in to read on mobile. But some other pages on the Dendron wiki can also be read normally on mobile without the need to zoom. 

## To Reproduce

The page that I need to zoom to read on mobile: https://wiki.dendron.so/notes/5U4eAiqshI67VxIL40KWH/

The page that can be read normally without zooming: https://wiki.dendron.so/notes/81da87be-2d4e-47b5-a1d6-c0d647e1ab00/

On mobile, Safari on iOS in my case, go to the 2 url cited previously.
We will see the differences in readability of each page at default zoom level. 

## Expected behavior

The readability of each published page should be consistent and fixed at default zoom level.

## Screenshots

View of page that need to zoom to read
![IMG_0417](https://user-images.githubusercontent.com/81280428/149543610-163f65e3-2f9e-4994-9a5c-ee29c9d1606d.PNG)

View of page that don't need to zoom
![IMG_0418](https://user-images.githubusercontent.com/81280428/149543651-8a425509-bcbf-41bc-bda7-9a8d590efb36.PNG)

## Desktop (please complete the following information)

- OS: iOS 14
- Browser: safari
- Version: 

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by SeriousBug** [comment]
Thanks for reporting the issue, I can see the broken layout too.

**Comment by kevinslin** [comment]
this has been fixed in v105.0

**Comment by andrey-jef** [comment]
> this has been fixed in v105.0

The situation is much better, but I doubt that the inconsistent layout bug still persists. Please consider to reopen the issue.

This is a screencap of a perfectly rendered on iOS.
![IMG_0445](https://user-images.githubusercontent.com/81280428/182704359-8e03388f-fa67-45b6-89f4-f2bdb5922987.PNG)

The two attached below are screencaps of the not-so-neat view, for comparison. The 2 visited urls are as follows

- https://wiki.dendron.so/
- https://wiki.dendron.so/notes/9MZBqhrijEM4QpZRa5t08/ 

![IMG_0444](https://user-images.githubusercontent.com/81280428/182704616-fe250cdd-f335-42a7-88a6-226c924b2cf1.PNG)
![IMG_0446](https://user-images.githubusercontent.com/81280428/182704673-021823e9-d8b3-4c93-8213-fcca2f755f6a.PNG)
