### ISSUE TITLE
Publishing crashes when customHeaderPath is set to any filename except header.html

### ISSUE THREAD

**Issue by dagriefaa** [dendronhq/dendron#2549]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Currently, `customHeaderPath` is not relative to workspace root, but `.next/public`, which results in a crash during publishing when it can't find the header file.

## To Reproduce
1. Add a HTML file in the workspace root to be used as the header (e.g. `header.html`)
2. Set `customHeaderPath` to `header.html`
3. Run command to export site
4. Observe exporting fails while generating pages (see additional context)

## Expected behavior
The site exports normally with injected header HTML.

## Desktop (please complete the following information)
- OS: Windows 10
- Browser (if with published websites; include version): Edge 98
- Dendron Version: v0.85.0

## Additional context
Relevant section of build log:
```
info  - Checking validity of types...
info  - Creating an optimized production build...
info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/121)
{
  stack: "Error: ENOENT: no such file or directory, open '/builds/dagriefaa/notes/.next/public/header.html'\n" +
    '    at Object.openSync (fs.js:476:3)\n' +
    '    at Object.readFileSync (fs.js:377:35)\n' +
    '    at getCustomHead (/builds/dagriefaa/notes/.next/.next/server/chunks/774.js:184:60)\n' +
    '    at async getStaticProps (/builds/dagriefaa/notes/.next/.next/server/pages/notes/[id].js:50:35)\n' +
    '    at async renderToHTML (/builds/dagriefaa/notes/.next/node_modules/next/dist/server/render.js:465:20)\n' +
    '    at async /builds/dagriefaa/notes/.next/node_modules/next/dist/export/worker.js:269:36\n' +
    '    at async Span.traceAsyncFn (/builds/dagriefaa/notes/.next/node_modules/next/dist/trace/trace.js:75:20)',
  message: "ENOENT: no such file or directory, open '/builds/dagriefaa/notes/.next/public/header.html'",
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/builds/dagriefaa/notes/.next/public/header.html'
}
```
The error message repeats about a hundred times.

Moving the header file to `.next/public` results in the expected behaviour.

**Comment by Harshita-mindfire** [comment]
Hello @dagriefaa, if `customHeaderPath` is set, `dendron publish dev` command exports the header.html from the path specified in custom header to `.next/public`. Can you try removing `.next` directory and running `dendron publish dev` again?

**Comment by Harshita-mindfire** [comment]
Update:  the `customHeaderPath` issue occurs only when there is a hyphen in the header filename (e.g. ci-header.html)
More info in [discord-thread](https://discordapp.com/channels/717965437182410783/950663274960146433/951818769657909279)

**Comment by sstiglitz** [comment]
I ran into a similar error, but was not using a custom header at all.

Still the suggestion to `rm -rf .next` and republish worked, thanks!

**Comment by Harshita-mindfire** [comment]
This should be fixed in v0.87 of Dendron. Feel free to comment here if not the same.

**Comment by dagriefaa** [comment]
Doesn't appear to be fixed; deployment still fails with same error under same conditions using v0.87 CLI.

[Test repo](https://gitlab.com/dagriefaa/publishing-with-nextjs)

**Comment by Harshita-mindfire** [comment]
Apologies for the late follow-up. This should be fixed in the latest versions of Dendron. Feel free to comment here if that is not the case.
