### ISSUE TITLE
The ()s in the url's image cause error with Dendron's extended image parser

### ISSUE THREAD

**Issue by andrey-jef** [dendronhq/dendron#2564]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When appending the css properties to an image, instead of applying the properties, Dendron shows the css text next to image. This error happens only with a specific url.

## To Reproduce

1. Create a markdown note with embedded image url
```markdown
Example
![example-current-liabilities](https://www.investopedia.com/thmb/aEVczlh4Rlnoc7CD-tyvgOKJW0g=/660x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/dotdash_Final_Current_Liabilities_Sep_2020-01-6515e265cfd34787ae2b0a30e9f1ccc8.jpg){max-width: 300px, display: block, margin: 0 auto}
```
- image url: 
    ```markdown
    https://www.investopedia.com/thmb/aEVczlh4Rlnoc7CD-tyvgOKJW0g=/660x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/dotdash_Final_Current_Liabilities_Sep_2020-01-6515e265cfd34787ae2b0a30e9f1ccc8.jpg
    ```
- appended css properties:
    ```css
    {max-width: 300px, display: block, margin: 0 auto}
    ```
2. Open `Dendron Preview` to show the note

## Expected behavior

The css properties should be applied to image display.

## Screenshots

![Screenshot 2022-03-14 023815](https://user-images.githubusercontent.com/81280428/158090413-99d8d85f-fca0-4e62-81d1-13e037145d0d.jpg)

## Desktop (please complete the following information)

- OS: Win 10
- Browser (if with published websites; include version): Opera, Version:84.0.4316.31
- Versions (all that apply to bug):
  - Dendron Extension: v0.85.0
  - VS Code version: VS Codium v1.65.2
  - Dendron CLI:

## Additional context

[comment from SeriousBug in discord](https://discord.com/channels/717965437182410783/735365126227493004/952739590907789352): the ()s in the url must be throwing off our extended image parser, so it falls back to the default parser which doesn't have the extended properties

**Comment by Harshita-mindfire** [comment]
Thanks for reporting the bug. We will let you know when this is fixed 🙏

**Comment by SeriousBug** [comment]
Hi! Thanks for the report, we have a fix coming which should be out soon.

In the meantime, I realized you can encode the parenthesis to make this work, by replacing `(` with `%28` and `)` with `%29`. For example,

`![alt](https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Pescatorea_%28Plate_XXIII%29_BHL36081367.jpg/411px-Pescatorea_%28Plate_XXIII%29_BHL36081367.jpg){ width: "300px" }`

If you go to that link, you'll see that the original URL has `(` and `)` characters in it. The image will show up in the preview.

**Comment by andrey-jef** [comment]
> Hi! Thanks for the report, we have a fix coming which should be out soon.
> 
> In the meantime, I realized you can encode the parenthesis to make this work, by replacing `(` with `%28` and `)` with `%29`. For example,
> 
> `![alt](https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Pescatorea_%28Plate_XXIII%29_BHL36081367.jpg/411px-Pescatorea_%28Plate_XXIII%29_BHL36081367.jpg){ width: "300px" }`
> 
> If you go to that link, you'll see that the original URL has `(` and `)` characters in it. The image will show up in the preview.

As u saw in my screenshot, the image can be displayed (but without css properties being applied) in the preview and published page. The problem is that the text of css properties will be appended next to the image.

Thanks for the workaround. It works as expected

**Comment by SeriousBug** [comment]
This has been fixed in Dendron 0.88. Could you please try it after updating?

**Comment by andrey-jef** [comment]
> This has been fixed in Dendron 0.88. Could you please try it after updating?

hmm, just recheck with dendron updated to v0.88.0. The problem still persisted, in both `Preview` and published page, as shown in the screencap below. Or do I need to modify anything?

in published page

![Screenshot 2022-03-30 121441](https://user-images.githubusercontent.com/81280428/160809656-160d980f-ec31-48a7-9d56-cb53508ae914.jpg)

in `Preview`

![Screenshot 2022-03-30 121408](https://user-images.githubusercontent.com/81280428/160809686-15896428-5117-4341-9eb6-8df19b497a6d.jpg)

**Comment by SeriousBug** [comment]
Ah, I think our release notes were incorrect on this. My bad, looks like it will be fixed in the next version.

**Comment by SeriousBug** [comment]
Sorry again for the confusion, this has been merged with Dendron 0.89.
