### ISSUE TITLE
enableHierarchyDisplay problem

### ISSUE THREAD

**Issue by wupingju** [dendronhq/dendron#2943]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I’ve tried to set `enableHierarchyDisplay` to false but my site still shows the Children section.

## To Reproduce

1. My codes are here: https://github.com/wupingju/pinchlime-dendron/blob/master/dendron.yml
2. This is my site: https://wiki.pinchlime.com/ 

## Expected behavior

If I set `enableHierarchyDisplay` to false, my site shouldn't show the Children section.

## Screenshots

https://media.discordapp.net/attachments/735365126227493004/976479018360639559/CleanShot-2022-05-18-21-38-08.png

## Desktop (please complete the following information)

- OS: macOS
- Browser (if with published websites; include version): Sidekick / Safari
- Versions (all that apply to bug):
  - Dendron Extension: Latest
  - VS Code version: Latest
  - Dendron CLI: 

## Dendron Log file

(I'll attach this file when I go home)

**Comment by Harshita-mindfire** [comment]
Thank @wupingju for reporting the bug. We'll let you know when this gets fixed 🙏

**Comment by Harshita-mindfire** [comment]
This should be fixed with Dendron v0.97. Feel free to comment here if that is not the case.

**Comment by Harshita-mindfire** [comment]
Hey @PJ Wu#4806 What is the dendron-cli version you have? 
Also can you try uncommenting this and see if that works https://github.com/wupingju/pinchlime-dendron/blob/master/dendron-publish-site.sh#L14?

**Comment by wupingju** [comment]
Hi @Harshita-mindfire 

I've tried to delete
# yarn add @dendronhq/dendron-cli@latest

but still the same~

I don't know how to check my dendron-cli version (don't remember if I've installed this), could you please tell me how to check?

**Comment by wupingju** [comment]
These are deploy logs , don't know if this will help.

<img width="991" alt="CleanShot-2022-06-01-21-55-19" src="https://user-images.githubusercontent.com/103130905/171422139-3d7e09b6-564f-4ec2-b12b-b08c055de9f7.png">
<img width="992" alt="CleanShot-2022-06-01-21-55-30" src="https://user-images.githubusercontent.com/103130905/171422154-9666dd14-bf33-4d9f-8513-29041315c692.png">
<img width="979" alt="CleanShot-2022-06-01-21-55-40" src="https://user-images.githubusercontent.com/103130905/171422170-e81f3556-3054-42e8-a07a-0d52f658a4af.png">
<img width="981" alt="CleanShot-2022-06-01-21-55-52" src="https://user-images.githubusercontent.com/103130905/171422237-34008a0b-9d55-4ed2-badb-953eaf2aa9eb.png">
<img width="979" alt="CleanShot-2022-06-01-21-56-04" src="https://user-images.githubusercontent.com/103130905/171422280-f87426c8-14ce-471e-b684-d54d24ddbe16.png">
<img width="973" alt="CleanShot-2022-06-01-21-56-18" src="https://user-images.githubusercontent.com/103130905/171422295-8ec44790-7c3a-4439-9949-b34870d1f808.png">
<img width="973" alt="CleanShot-2022-06-01-21-56-29" src="https://user-images.githubusercontent.com/103130905/171422311-27acaeaf-d27f-48eb-9831-d2ebe0d61162.png">

**Comment by wupingju** [comment]
Oh I see!!! (I tried the second solution)
I misunderstood the meaning of uncommenting, now it works!!!

Thank you very very much!
