### ISSUE TITLE
Snippets and Native Workspace

### ISSUE THREAD

**Issue by ebromberg** [dendronhq/dendron#3225]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug
I created a Native Workspace in VSCode. When I go to use the predefined snippets, they are not working. If I create a Code Workspace, they function just fine. 

## To Reproduce

1. Open an existing project
2. Goto Dendron: Initialize Workspace
3. Choose Native.
4. Create a new note 
5. Try using the todo snippet by typing to [tab] nothing comes up (even typing to and ctrl-space shows no snippet)

## Expected behavior

Snippet should work
## Desktop (please complete the following information)

- OS: Windows 10
- Browser (if with published websites; include version): Chrome Version 103.0.5060.114 (Official Build) (64-bit)
- Versions (all that apply to bug):
  - Dendron Extension: v0.102.0
  - VS Code version: 1.69.0
  - Dendron CLI:

## Additional context

{"level":30,"time":1657574614784,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1657574614842,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"c:\\Users\\EBromberg\\AppData\\Roaming\\Code\\logs\\20220711T165221\\exthost1\\dendron.dendron","extensionPath":"c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.102.0","extensionUri":"c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.102.0","workspaceFolders":["c:\\Projects\\npc_ansible"]}
{"level":30,"time":1657574614862,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1657574614863,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1657574614863,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1657574614863,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1657574614864,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"anonymous id","anonymousId":"l0e8eyabj37eg7x2ostjof1"}
{"level":30,"time":1657574614871,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1657574628967,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"NATIVE","currentVersion":"0.102.0","previousGlobalVersion":"0.102.0","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1657574629480,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceActivator.init:postSetupTraits","wsRoot":"c:\\Projects\\npc_ansible\\notes"}
{"level":30,"time":1657574629514,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"runMigrationsIfNecessary","changes":[],"workspaceInstallStatus":"NO_CHANGE"}
{"level":30,"time":1657574629514,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceActivator.init:postMigration","wsRoot":"c:\\Projects\\npc_ansible\\notes"}
{"level":30,"time":1657574629525,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceActivator.init:postWsServiceInitialize","wsRoot":"c:\\Projects\\npc_ansible\\notes"}
{"level":30,"time":1657574629533,"pid":15332,"hostname":"AP-PF1Y22SP","name":"execServer","state":"enter"}
{"level":30,"time":1657574631158,"pid":15332,"hostname":"AP-PF1Y22SP","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1657574632537,"pid":10352,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1657574632537,"pid":10352,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1657574632538,"pid":10352,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1657574632538,"pid":10352,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1657574632539,"pid":10352,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"anonymous id","anonymousId":"l0e8eyabj37eg7x2ostjof1"}
{"level":30,"time":1657574633264,"pid":15332,"hostname":"AP-PF1Y22SP","name":"execServer","state":"message","message":"50837"}
{"level":30,"time":1657574633265,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":10352}
{"level":30,"time":1657574633265,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"startServerProcess","msg":"post-start-server","port":50837,"durationStartServer":3734}
{"level":30,"time":1657574633267,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceActivator.init:verifyOrStartServerProcess","port":50837}
{"level":30,"time":1657574633275,"pid":15332,"hostname":"AP-PF1Y22SP","name":"logger","ctx":"FileStorageV2","wsRoot":"c:\\Projects\\npc_ansible\\notes","vaults":[{"fsPath":".","selfContained":true,"name":"notes"}],"level":"info"}
{"level":30,"time":1657574633276,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceActivator.init:exit"}
{"level":30,"time":1657574633280,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1657574633280,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1657574633280,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1657574633281,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"anonymous id","anonymousId":"l0e8eyabj37eg7x2ostjof1"}
{"level":30,"time":1657574633281,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1657574633281,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","msg":"Segment Residual Cache Path is at c:\\Users\\EBromberg\\AppData\\Roaming\\Code\\User\\globalStorage\\dendron.dendron\\segmentresidualcache.log"}
{"level":30,"time":1657574633281,"pid":15332,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1657574633283,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"_activate:postSetupWorkspace","platform":"win32","extensions":[{"id":"dendron.dendron","version":"0.102.0","active":true},{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts"},{"id":"redhat.vscode-yaml","version":"1.8.0","active":false}],"vaults":[{"fsPath":".","selfContained":true,"name":"notes"}]}
{"level":30,"time":1657574634020,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1657574634021,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1657574634022,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1657574634022,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1657574634755,"pid":10352,"hostname":"AP-PF1Y22SP","name":"logger","ctx":"parsingSchemas","fname":"root","root":{"fsPath":".","selfContained":true,"name":"notes"},"imports":[]}
{"level":30,"time":1657574635254,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":566}
{"level":30,"time":1657574635255,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1657574635255,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1657574635261,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1657574635262,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1657574635271,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1657574635271,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1657574635271,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1657574635271,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
{"level":30,"time":1657574635479,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceActivator:activate","msg":"fin startClient","durationReloadWorkspace":1256}
{"level":30,"time":1657574635479,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1657574635488,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"togglePluginActiveContext","state":"togglePluginActiveContext: true"}
{"level":30,"time":1657574635504,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.102.0","previousExtensionVersion":"0.0.0"}
{"level":30,"time":1657574650739,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","msg":"sendSavedAnalytics"}
{"level":30,"time":1657574650740,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"AnalyticsUtils.sendSavedAnalytics","message":"start"}
{"level":40,"time":1657574650740,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"AnalyticsUtils.sendSavedAnalytics","msg":"failed to read the saved telemetry dir","telemetryDir":"C:\\Users\\EBromberg\\.dendron\\saved-telemetry"}
{"level":30,"time":1657574779475,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1657574779477,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574809064,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Projects\\npc_ansible\\notes\\notes\\ansible.pr.md"]}
{"level":30,"time":1657574809067,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574809075,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"c:\\Projects\\npc_ansible\\notes\\notes\\ansible.pr.md"}
{"level":30,"time":1657574809079,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"ansible.pr"}
{"level":30,"time":1657574810484,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"exit","fname":"ansible.pr"}
{"level":30,"time":1657574811634,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574812573,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574812732,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574812891,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574813234,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574813446,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"provideCompletionItems","position":{"line":10,"character":2},"msg":"enter"}
{"level":30,"time":1657574818367,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1657574818368,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574818369,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Projects\\npc_ansible\\.vscode\\.dendron.code-snippets"]}
{"level":30,"time":1657574818371,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574823969,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1657574823970,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574824012,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Projects\\npc_ansible\\.vscode\\settings.json"]}
{"level":30,"time":1657574824013,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574824014,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"settings.json"}
{"level":30,"time":1657574825898,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1657574825900,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574825901,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Projects\\npc_ansible\\.vscode\\.dendron.code-snippets"]}
{"level":30,"time":1657574825903,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574829237,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1657574829238,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574829322,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Projects\\npc_ansible\\.vscode\\settings.json"]}
{"level":30,"time":1657574829323,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574831104,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1657574831105,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574831110,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Projects\\npc_ansible\\notes\\notes\\ansible.pr.md"]}
{"level":30,"time":1657574831111,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574831114,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"c:\\Projects\\npc_ansible\\notes\\notes\\ansible.pr.md"}
{"level":30,"time":1657574832400,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574833230,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"c:\\Projects\\npc_ansible\\notes\\notes\\ansible.pr.md","reason":"Manual","msg":"enter"}
{"level":30,"time":1657574833233,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveNote","match":["updated: 1657574277798","1657574277798"],"msg":"update activeText editor"}
{"level":30,"time":1657574833243,"pid":10352,"hostname":"AP-PF1Y22SP","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":0,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1657574833349,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1657574833460,"pid":10352,"hostname":"AP-PF1Y22SP","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":0,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1657574833483,"pid":10352,"hostname":"AP-PF1Y22SP","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":0,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1657574833490,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1657574833500,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574833972,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"c:\\Projects\\npc_ansible\\notes\\notes\\ansible.pr.md","reason":"Manual","msg":"enter"}
{"level":30,"time":1657574834774,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574834850,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574835091,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574835192,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574835361,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"provideCompletionItems","position":{"line":10,"character":2},"msg":"enter"}
{"level":30,"time":1657574836300,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"provideCompletionItems","position":{"line":10,"character":1},"msg":"enter"}
{"level":30,"time":1657574836377,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574836545,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574836725,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574837040,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574837584,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574846271,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"NoteLookupCommand:gatherInput","msg":"enter"}
{"level":30,"time":1657574846277,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"LookupControllerV3:new","msg":"enter"}
{"level":30,"time":1657574846280,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"prepareQuickPick","msg":"enter"}
{"level":30,"time":1657574846285,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"prepareQuickPick","msg":"exit"}
{"level":30,"time":1657574846289,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"showQuickPick","msg":"enter"}
{"level":30,"time":1657574846289,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:pre"}
{"level":30,"time":1657574846289,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"showQuickPick","msg":"exit"}
{"level":30,"time":1657574846303,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"ansible.pr","justActivated":true}
{"level":30,"time":1657574846309,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"enter"}
{"level":30,"time":1657574846310,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"exit"}
{"level":30,"time":1657574846310,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574846311,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":7}
{"level":30,"time":1657574846311,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"ansible.pr","profile":8,"cancelled":false}
{"level":30,"time":1657574846429,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"ansible.pr","justActivated":false,"prevQuickpickValue":"ansible.pr"}
{"level":30,"time":1657574846429,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"ansible.pr","profile":0,"cancelled":false}
{"level":30,"time":1657574848245,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"te","justActivated":false,"prevQuickpickValue":"ansible.pr"}
{"level":30,"time":1657574848252,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574848253,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":6}
{"level":30,"time":1657574848262,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"te","profile":17,"cancelled":false}
{"level":30,"time":1657574848480,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test","justActivated":false,"prevQuickpickValue":"te"}
{"level":30,"time":1657574848485,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574848485,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":4}
{"level":30,"time":1657574848496,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test","profile":16,"cancelled":false}
{"level":30,"time":1657574849094,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"testin","justActivated":false,"prevQuickpickValue":"test"}
{"level":30,"time":1657574849100,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574849101,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":6}
{"level":30,"time":1657574849112,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"testin","profile":18,"cancelled":false}
{"level":30,"time":1657574849235,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"testing","justActivated":false,"prevQuickpickValue":"testin"}
{"level":30,"time":1657574849240,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574849241,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":4}
{"level":30,"time":1657574849245,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"testing","profile":9,"cancelled":false}
{"level":30,"time":1657574849408,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"testing.","justActivated":false,"prevQuickpickValue":"testing"}
{"level":30,"time":1657574849412,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574849412,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":4}
{"level":30,"time":1657574849413,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"testing.","profile":5,"cancelled":false}
{"level":30,"time":1657574850143,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"testing.s","justActivated":false,"prevQuickpickValue":"testing."}
{"level":30,"time":1657574850145,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574850145,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":2}
{"level":30,"time":1657574850147,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"testing.s","profile":3,"cancelled":false}
{"level":30,"time":1657574850253,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"testing.sn","justActivated":false,"prevQuickpickValue":"testing.s"}
{"level":30,"time":1657574850258,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574850258,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":4}
{"level":30,"time":1657574850262,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"testing.sn","profile":8,"cancelled":false}
{"level":30,"time":1657574850395,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"testing.sni","justActivated":false,"prevQuickpickValue":"testing.sn"}
{"level":30,"time":1657574850400,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574850401,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":4}
{"level":30,"time":1657574850404,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"testing.sni","profile":9,"cancelled":false}
{"level":30,"time":1657574850585,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"testing.snip","justActivated":false,"prevQuickpickValue":"testing.sni"}
{"level":30,"time":1657574850591,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574850592,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":6}
{"level":30,"time":1657574850596,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"testing.snip","profile":11,"cancelled":false}
{"level":30,"time":1657574850851,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"testing.snippet","justActivated":false,"prevQuickpickValue":"testing.snip"}
{"level":30,"time":1657574850855,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574850856,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":4}
{"level":30,"time":1657574850860,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"testing.snippet","profile":9,"cancelled":false}
{"level":30,"time":1657574851180,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"NoteLookupProvider:onDidAccept","quickpick":"testing.snippets"}
{"level":30,"time":1657574851181,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"testing.snippets","justActivated":false,"prevQuickpickValue":"testing.snippet"}
{"level":30,"time":1657574851183,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1657574851183,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":2}
{"level":30,"time":1657574851186,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"testing.snippets","profile":4,"cancelled":false}
{"level":30,"time":1657574851201,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.lookupNote:run","msg":"pre-execute"}
{"level":30,"time":1657574851201,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"NoteLookupCommand:execute","msg":"enter"}
{"level":30,"time":1657574851204,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"c:\\Projects\\npc_ansible\\notes\\notes\\ansible.pr.md"}
{"level":30,"time":1657574851204,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":".","selfContained":true,"name":"notes"}}
{"level":30,"time":1657574851216,"pid":10352,"hostname":"AP-PF1Y22SP","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":0,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1657574851233,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1657574851237,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"FileWatcher:onDidCreate","fsPath":"c:\\Projects\\npc_ansible\\notes\\notes\\testing.snippet.md"}
{"level":30,"time":1657574851304,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1657574851305,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574851310,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Projects\\npc_ansible\\notes\\notes\\testing.snippet.md"]}
{"level":30,"time":1657574851311,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657574851315,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"c:\\Projects\\npc_ansible\\notes\\notes\\testing.snippet.md"}
{"level":30,"time":1657574851316,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"testing.snippet"}
{"level":30,"time":1657574851759,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"LookupControllerV3:onHide","msg":"exit"}
{"level":30,"time":1657574851759,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"NoteLookupCommand:execute","msg":"exit"}
{"level":30,"time":1657574851760,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.lookupNote:run","msg":"post-execute"}
{"level":30,"time":1657574851775,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"exit","fname":"testing.snippet"}
{"level":30,"time":1657574852614,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574853403,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574853496,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574854242,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"provideCompletionItems","position":{"line":7,"character":2},"msg":"enter"}
{"level":30,"time":1657574856533,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574857299,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"provideCompletionItems","position":{"line":7,"character":4},"msg":"enter"}
{"level":30,"time":1657574858618,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574859349,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657574865924,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1657574865925,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1657574865942,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1657574866050,"pid":15332,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}

**Comment by hikchoi** [comment]
Hey @ebromberg, thank you for the report.

I can't seem to reproduce this on my end, I've tried initializing a fresh native workspace and snippets are resolved fine.

From the logs, I see that you are creating notes through lookup, so I don't think this has to do with the file not being in the scope of where dendron's snippets works (markdown + yaml). 

It may be that where you initialized the native workspace (the existing project) has a project-scoped snippet that is somehow conflicting with what `dendron.code-snippets` is providing.

Can you try `Preferences: Configure User Snippets` in the command palette and see if there are any snippets that may conflict?

You also mentioned it doesn't show up in the suggestions. Can you check if you get any snippet suggestions at all when you use `Trigger Suggest` in an empty line?

**Comment by hikchoi** [comment]
Thank you for providing the steps. I managed to reproduce the issue.

The issue is that we create the user defined code snippet file `dendron.code-snippets` under the directory `/documents/.vscode`.

Fo the user defined code snippt file to be recognized in VSCode, the project root (your project `NV` in this case) should be where the `.vscode` directory exists, or alternatively the workspace needs to become a [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

This requires that your project `NV` has the path to `documents` set as a folder. We currently do not add this automatically when creating a native workspace because it would be modifying the existing project's `.code-workspace` file.

In the meantime, you can follow the steps described  [here](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_add-folder-to-workspace) to make the snippets work as expect.

We'll discuss how we want to handle this; it will either be modifying the project's workspace setting anyways vs creating an extension scoped snippet instead so it isn't tied to how the workspace. We'll let you know in this issue when it gets resolved.

**Comment by ebromberg** [comment]
I added the documents folder to the workspace as the link suggested. The snippets still do not work. Steps I took:1) Opened my NV folder in VSCode.2) File->Add Folder to workspace3) Chose documents folder under NV.Tried typing to and tab. Nothing happened. Trigger Suggestions came back with none found. Did I miss something?On Jul 14, 2022, at 9:53 AM, Mark Hyunik Choi ***@***.***> wrote:Thank you for providing the steps. I managed to reproduce the issue.The issue is that we create the user defined code snippet file dendron.code-snippets under the directory /documents/.vscode.Fo the user defined code snippt file to be recognized in VSCode, the project root (your project NV in this case) should be where the .vscode directory exists, or alternatively the workspace needs to become a multi-root workspace.This requires that your project NV has the path to documents set as a folder. We currently do not add this automatically when creating a native workspace because it would be modifying the existing project's .code-workspace file.In the meantime, you can follow the steps described here to make the snippets work as expect.We'll discuss how we want to handle this; it will either be modifying the project's workspace setting anyways vs creating an extension scoped snippet instead so it isn't tied to how the workspace. We'll let you know in this issue when it gets resolved.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ebromberg** [comment]
Just wondering if there was any update on this. As stated before I made this a multi-root workspace but the snippets still do not work. Below is what my folder structure looks like now. 
![image](https://user-images.githubusercontent.com/48656450/180845847-a3c7ff78-bd30-432b-9e5b-1afca69d6d8f.png)
