### ISSUE TITLE
Custom color tags no longer working

### ISSUE THREAD

**Issue by EngineerFaunce** [dendronhq/dendron#3605]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The `color` attribute in a tag's frontmatter no longer works.

## To Reproduce

1. Create a tag with the `color` attribute in the frontmatter set to some value (I used `color: "#cc99ff"`
2. Reload window
3. Add tag to a note

## Expected behavior

Tags to display the color defined in their frontmatter.

## Screenshots

Tag with `color` attribute set:
![image](https://user-images.githubusercontent.com/16312436/192919452-f9dd5e8e-f6e4-49bb-99ad-ac1f8620621d.png)

Tag as it appears in a note:
![image](https://user-images.githubusercontent.com/16312436/192919494-4e3c5647-33a1-41fc-a47e-c1a35b071bb0.png)

Actual color:
![image](https://user-images.githubusercontent.com/16312436/192919647-c87570d7-37fc-46c6-89c8-f73857c28ab1.png)

## Desktop (please complete the following information)

- OS: Windows 10
- Versions (all that apply to bug):
  - Dendron Extension: v0.114.0
  - VS Code version: 1.71.2

## Additional context

Example from the dendron documentation: https://wiki.dendron.so/notes/zDqYUhNE10HXlmStfqwVD/

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/9670102/dendron.log)

**Comment by kevinslin** [comment]
thanks for the issue, we're looking into this!

**Comment by Harshita-mindfire** [comment]
This should be fixed after Dendron v0.116. Feel free to comment here if this is still an issue.

**Comment by EngineerFaunce** [comment]
I've updated to Dendron v0.116.0, but the custom color tag still isn't working:

![image](https://user-images.githubusercontent.com/16312436/198856517-fa3030ec-c883-4e79-9385-0f59e93dd9e6.png)

![image](https://user-images.githubusercontent.com/16312436/198856521-36685a26-3c23-4e8c-b069-eb404bcabb0c.png)

![image](https://user-images.githubusercontent.com/16312436/198856532-838b6abb-77aa-4033-b586-15a7251251ca.png)

**Comment by Harshita-mindfire** [comment]
Hmm.. unable to repro this on my end. Can you try saving the document with color and reload window?

**Comment by EngineerFaunce** [comment]
That didn't change anything unfortunately. Something that may be of interest though, the examples on the Dendron wiki for tag custom colors are also not working correctly: https://wiki.dendron.so/notes/8bc9b3f1-8508-4d3a-a2de-be9f12ef1821/#custom-colors

![image](https://user-images.githubusercontent.com/16312436/199008791-367f9151-f23d-41d9-b3d9-b286e1abf249.png)

The `#blue` example tag is set to `#1E32E6`: 

![image](https://user-images.githubusercontent.com/16312436/199009051-2add1190-dd7b-4ef4-a38b-0d34a0c08075.png)

**Comment by Harshita-mindfire** [comment]
Got it. Will keep this open

**Comment by EngineerFaunce** [comment]
This seems to have been fixed in Dendron v0.118.0. Thank you!

![image](https://user-images.githubusercontent.com/16312436/203441785-a9a1e993-d28d-4686-9f73-f9724a626d0b.png)

![image](https://user-images.githubusercontent.com/16312436/203441807-900fc081-01a6-4db0-90c6-1a84ae82a8b4.png)

**Comment by airborn** [comment]
I think that this problem is still occurring to me in v0.119.0:
![image](https://user-images.githubusercontent.com/68899/224161574-67580fd5-839a-4d3e-8e9b-2a0474c4da42.png)

I have also noticed that as soon as I use the tag in the note body not only in frontmatter, the color is rendered correctly:
![image](https://user-images.githubusercontent.com/68899/224161883-19718aa2-8345-4e3f-904f-2dfb322bb5a1.png)

**Comment by CarloDePieri** [comment]
I'm still facing this issue, on `v0.123.0`, both with textual color names and hex codes.
Having the tag both in the frontmatter and in the note body does not seems to solve the problem for me.

**Comment by Luk164** [comment]
I think I am also having this issue. Why is it closed if multiple people keep confirming it is still present?

**Comment by mvherweg** [comment]
Like Luk above, experiencing this as well in v 0.123.0

**Comment by pjmattingly** [comment]
Still experiencing this issue. @Harshita-mindfire would it be possible to re-open this item? There seems to be several people affected. =/

**Comment by cindrmon** [comment]
Still having the same issue using v0.124.0. hopefully this issue should be reopened.
