### ISSUE TITLE
The v0.120.0 and later won't be activated

### ISSUE THREAD

**Issue by sailing-innocent** [dendronhq/dendron#3926]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When I updated the release v0.120.0 and later, then it could not be activated automately when I start my workspace.

## To Reproduce

My Machine is Windows10 with vscode v1.78.0

1. open vscode
2. update dendron v0.112.0 and above
3. no dendron is activated at all

## Expected behavior

just as v0.119.0 did

**Comment by labriola** [comment]
It's dead in the water. I had downgraded to 119.0. Newer version won't even start enough to allow me to see logs to aid in debugging.

**Comment by kevinslin** [comment]
Thanks for the report and apologies for that. just published 0.121.0 which should fix the issue. could you confirm whether this fixes it for you?

**Comment by labriola** [comment]
It does not fix the issue for me. 0.122.0 is installed and I restated. After a restart, dendron does not not seem to start. Attempting to open logs yields the error message Command 'Dendron:Dev: Open Logs' resulted in an error command 'dendron.dev.openLogs' not found. Similar for all other commands

**Comment by kevinslin** [comment]
@labriola what is your operating system?

**Comment by fr4nt1x** [comment]
If it helps, i have the same behaviour on Windows 10 10.0.19044 Build 19044


Dendron startup works fine for 0.119.0 but doesn't work for 0.120.0, 0.121.0, 0.122.0.

I see the following error inside the output for the extension host:
```
2023-05-05 08:37:33.588 [error] Activating extension dendron.dendron failed due to an error:
2023-05-05 08:37:33.589 [error] Error: \\?\c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\node_sqlite3.node is not a valid Win32 application.
\\?\c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\node_sqlite3.node
	at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
	at Module._extensions..node (node:internal/modules/cjs/loader:1273:18)
	at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at b._load (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:29948)
	at h._load (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:26698)
	at I._load (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:24489)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Tools\VSCode\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\sqlite3-binding.js:1:165)
	at u._compile (c:\Tools\VSCode\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at b._load (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:29948)
	at h._load (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:26698)
	at I._load (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:24489)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Tools\VSCode\resources\app\out\vs\loader.js:4:647)
	at 49326 (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:3819717)
	at __webpack_require__ (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5032458)
	at 40682 (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:2945094)
	at __webpack_require__ (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5032458)
	at 45708 (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:2:821717)
	at __webpack_require__ (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5032458)
	at 70666 (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:2:832289)
	at __webpack_require__ (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5032458)
	at 34609 (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:2:785624)
	at __webpack_require__ (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5032458)
	at 1733 (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:2:779591)
	at __webpack_require__ (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5032458)
	at 97563 (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:2:821544)
	at __webpack_require__ (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5032458)
	at 59523 (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:2:870089)
	at __webpack_require__ (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5032458)
	at 4813 (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:3526643)
	at __webpack_require__ (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5032458)
	at c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5034180
	at Object.<anonymous> (c:\Users\USER\.vscode\extensions\dendron.dendron-0.120.0-win32-ia32\dist\extension.js:8:5034264)
	at u._compile (c:\Tools\VSCode\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at b._load (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:29948)
	at h._load (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:26698)
	at I._load (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:24489)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (c:\Tools\VSCode\resources\app\out\vs\loader.js:5:98)
	at v.rb (c:\Tools\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:27962)
	at async Promise.all (index 0)
```

**Comment by TeslaWebber** [comment]
Facing the same issue since version 0.120.0
Even after upgrading to version 0.122.0
OS: Windows 11 Version 22H2 Build Number:22621.1635
Editor: Visual Studio Code Version:1.78.0

**Comment by ads40** [comment]
Same situation as @labriola. Downgrading to 0.119.0 restores functionality.

Dendron 0.122.0
Ubuntu 20.04 in WSL2 on Windows 10
VSCode version 1.78

When trying to run Dendron 0.122.0, the output in Extension Host (Remote) contains this error:

```
2023-05-05 17:45:13.058 [error] Activating extension dendron.dendron failed due to an error:
2023-05-05 17:45:13.058 [error] Error: /home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/node_sqlite3.node: invalid ELF header
	at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
	at Module.load (node:internal/modules/cjs/loader:1004:32)
	at Function.Module._load (node:internal/modules/cjs/loader:839:12)
	at Function.b._load (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:127:29948)
	at Function.h._load (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:127:26698)
	at Function.I._load (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:91:24489)
	at Module.require (node:internal/modules/cjs/loader:1028:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/sqlite3-binding.js:1:103)
	at Module._compile (node:internal/modules/cjs/loader:1126:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
	at Module.load (node:internal/modules/cjs/loader:1004:32)
	at Function.Module._load (node:internal/modules/cjs/loader:839:12)
	at Function.b._load (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:127:29948)
	at Function.h._load (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:127:26698)
	at Function.I._load (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:91:24489)
	at Module.require (node:internal/modules/cjs/loader:1028:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.49326 (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:3819717)
	at __webpack_require__ (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5032458)
	at Object.40682 (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:2945094)
	at __webpack_require__ (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5032458)
	at Object.45708 (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:2:821717)
	at __webpack_require__ (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5032458)
	at Object.70666 (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:2:832289)
	at __webpack_require__ (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5032458)
	at Object.34609 (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:2:785624)
	at __webpack_require__ (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5032458)
	at Object.1733 (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:2:779591)
	at __webpack_require__ (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5032458)
	at Object.97563 (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:2:821544)
	at __webpack_require__ (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5032458)
	at Object.59523 (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:2:870089)
	at __webpack_require__ (/home/ads_USERon_wsl/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5032458)
	at Module.4813 (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:3526643)
	at __webpack_require__ (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5032458)
	at /home/ads_on_wsl/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5034180
	at Object.<anonymous> (/home/USER/.vscode-server/extensions/dendron.dendron-0.122.0-linux-x64/dist/extension.js:8:5034264)
	at Module._compile (node:internal/modules/cjs/loader:1126:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
	at Module.load (node:internal/modules/cjs/loader:1004:32)
	at Function.Module._load (node:internal/modules/cjs/loader:839:12)
	at Function.b._load (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:127:29948)
	at Function.h._load (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:127:26698)
	at Function.I._load (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:91:24489)
	at Module.require (node:internal/modules/cjs/loader:1028:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/loader.js:5:98)
	at v.rb (/home/USER/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/out/vs/workbench/api/node/extensionHostProcess.js:127:27962)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 0)
```

**Comment by sailing-innocent** [comment]
> Thanks for the report and apologies for that. just published 0.121.0 which should fix the issue. could you confirm whether this fixes it for you?

sad that v0.122.0 still can't fix the issue, all the dendron commands are registered but raise a not found error. perhaps the core crashed behind.

**Comment by denisrossetre** [comment]
Can confirm that I have the same problem and that downgrading to 0.119.0 works.

**Comment by Alpenblick** [comment]
Can confirm that I have the same problem and that downgrading to 0.119.0 works. 
Visual Studio Code: 1.78.0
Windows 10 Pro, OS build: 19045.2846

**Comment by mdger** [comment]
Same for me:
Visual Studio Code: 1.78.0
OS: Ubuntu 22.xx LTS

**Comment by labriola** [comment]
I can reproduce the issue on Ubuntu 22.x and Windows 10.x with Vscode 1.78.0.

**Comment by kevinslin** [comment]
the issue was that we switched from publishing a universal extension to platform specific extensions to support bundling sqlite. there were some issues with the binaries on certain distributions. have rolled back to the universal distribution in 0.123. issue should be fixed now

**Comment by kbudde** [comment]
I can confirm: Windows 11 with WSL + dendron 0.123.0 is working again.
Thank you
